name: mobile_mcp_workspace

packages:
  - packages/**
  - example_host
  - example_tool

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: dart analyze .
    exec:
      concurrency: 1
    packageFilters:
      dirExists: lib

  test:
    run: flutter test
    exec:
      concurrency: 1
    packageFilters:
      dirExists: test
